"""Initial migration

Revision ID: 91101a4ebea2
Revises: 
Create Date: 2024-06-12 20:09:41.082265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91101a4ebea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_images',
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_images_path'), 'service_images', ['path'], unique=False)
    op.create_index(op.f('ix_service_images_uploaded_by'), 'service_images', ['uploaded_by'], unique=False)
    op.create_table('service_tags',
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('images_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tags_name'), 'service_tags', ['name'], unique=False)
    op.create_index(op.f('ix_service_tags_type'), 'service_tags', ['type'], unique=False)
    op.create_table('service_relation_tag_image',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['service_images.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['service_tags.id'], ),
    sa.PrimaryKeyConstraint('image_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_relation_tag_image')
    op.drop_index(op.f('ix_service_tags_type'), table_name='service_tags')
    op.drop_index(op.f('ix_service_tags_name'), table_name='service_tags')
    op.drop_table('service_tags')
    op.drop_index(op.f('ix_service_images_uploaded_by'), table_name='service_images')
    op.drop_index(op.f('ix_service_images_path'), table_name='service_images')
    op.drop_table('service_images')
    # ### end Alembic commands ###
