"""Added trash field to image

Revision ID: 52599c6cb4f5
Revises: 91101a4ebea2
Create Date: 2024-06-13 00:59:58.464597

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52599c6cb4f5"
down_revision = "91101a4ebea2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_images",
        sa.Column(
            "trash", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_images", "trash")
    # ### end Alembic commands ###
